# fly.toml app configuration file generated for tetris-node on 2023-07-07T01:26:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tetris-node"
primary_region = "ams"

[[mounts]]
  source = "highscores"
  destination = "/mnt/highscores"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
